name: thanks_by
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  intl: ^0.19.0
  fl_chart: ^0.68.0
  provider: ^6.1.2
  flutter_form_builder: ^9.4.0
  fluttertoast: ^8.2.6
  table_calendar: ^3.1.2
  animations: ^2.0.11
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

